import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = (
    <header className="flex items-center justify-between p-4">
      <Link href="/">
        <h1 className="text-xl font-bold cursor-pointer">Home</h1>
      </Link>
    </header>
  );

  const footer = (
    <footer className="p-4">
      <p className="text-center text-sm">Powered by Bergen MIJ</p>
    </footer>
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between bg-black text-white flex-col min-h-screen">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
